default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: games_development
  host: 'localhost'

test:
  <<: *default
  database: games_test

production:
  <<: *default
  database: games
